-- MASTER FARMERS FACTORY DATABASE SEED SCRIPT
-- This script ensures the database ONLY contains products that exist in the /public folder.

-- STEP 1: Fix the database structure
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_seasonal BOOLEAN DEFAULT FALSE;

-- STEP 2: Clear old data to ensure ONLY these products exist
DELETE FROM products;

-- STEP 3: Insert all 61 products with correct image paths
INSERT INTO products (name, category, price, image_url, description, stock, unit, is_active, is_seasonal) VALUES
-- VEGETABLES
('Beetroot', 'Vegetables', 45.00, '/Vegetables/beetroot.jfif', 'Fresh and earthy beetroots, rich in nutrients.', 100, 'kg', true, false),
('Bitter Gourd', 'Vegetables', 35.00, '/Vegetables/bitter-gourd.jpg', 'Fresh bitter gourd, great for healthy cooking.', 100, 'kg', true, false),
('Bottle Gourd', 'Vegetables', 30.00, '/Vegetables/BottleGourd.jfif', 'Hydrating and fresh bottle gourd.', 100, 'kg', true, false),
('Brinjal', 'Vegetables', 40.00, '/Vegetables/Brinjal.jfif', 'Fresh purple brinjals, perfect for curries.', 100, 'kg', true, false),
('Cabbage', 'Vegetables', 25.00, '/Vegetables/Cabbage.jfif', 'Crunchy and fresh green cabbage.', 100, 'kg', true, false),
('Capsicum Green', 'Vegetables', 80.00, '/Vegetables/CapsicumGreen.jfif', 'Fresh green capsicum, perfect for salads.', 100, 'kg', true, false),
('Carrot (Ooty)', 'Vegetables', 60.00, '/Vegetables/ooty-carrot.jpg', 'Sweet and crunchy farm carrots.', 100, 'kg', true, false),
('Cauliflower', 'Vegetables', 45.00, '/Vegetables/Cauliflower.jfif', 'Fresh white cauliflower heads.', 100, 'kg', true, false),
('Coriander Leaves', 'Vegetables', 10.00, '/Vegetables/CorianderLeaves.jfif', 'Fresh and aromatic coriander leaves.', 100, 'bundle', true, false),
('Drumstick', 'Vegetables', 15.00, '/Vegetables/drumstick.jpg', 'Fresh drumsticks for sambar and curries.', 100, 'piece', true, false),
('Green Chilli', 'Vegetables', 40.00, '/Vegetables/Greenchili.jfif', 'Spicy fresh green chillies.', 100, 'kg', true, false),
('Ladies Finger', 'Vegetables', 35.00, '/Vegetables/LadiesFinger.jfif', 'Fresh okra, perfect for fry or curry.', 100, 'kg', true, false),
('Mint Leaves', 'Vegetables', 10.00, '/Vegetables/MintLeaves.jfif', 'Fresh mint leaves for chutney and tea.', 100, 'bundle', true, false),
('Onion (Red)', 'Vegetables', 45.00, '/Vegetables/Onionred.jfif', 'Farm fresh red onions.', 100, 'kg', true, false),
('Potato', 'Vegetables', 35.00, '/Vegetables/potato.jfif', 'Quality potatoes from local farms.', 100, 'kg', true, false),
('Pumpkin (Yellow)', 'Vegetables', 30.00, '/Vegetables/PumpkinYellow.jfif', 'Sweet and fresh orange pumpkin.', 100, 'kg', true, false),
('Radish', 'Vegetables', 25.00, '/Vegetables/Radish.jfif', 'Fresh white radish with greens.', 100, 'kg', true, false),
('Snake Gourd', 'Vegetables', 30.00, '/Vegetables/SnakeGourd.jfif', 'Fresh and long snake gourds.', 100, 'kg', true, false),
('Tomato (Country)', 'Vegetables', 30.00, '/Vegetables/TomatoCountry.jfif', 'Juicy red farm tomatoes.', 100, 'kg', true, false),
('Garlic', 'Vegetables', 120.00, '/Vegetables/Garlic.jfif', 'Fresh organic garlic bulbs, essential for seasoning.', 100, 'kg', true, false),
('Ginger', 'Vegetables', 100.00, '/Vegetables/Ginger.jfif', 'Fresh and aromatic ginger root.', 100, 'kg', true, false),
('Lemon', 'Vegetables', 5.00, '/Vegetables/lemon.jfif', 'Juicy fresh lemons, rich in Vitamin C.', 100, 'piece', true, false),
('French Beans', 'Vegetables', 60.00, '/Vegetables/Beans.jfif', 'Fresh green french beans, crunchy and sweet.', 100, 'kg', true, false),
('Green Peas', 'Vegetables', 80.00, '/Vegetables/GreenPeas.jfif', 'Fresh green peas, sweet and nutritious.', 100, 'kg', true, false),
('Cucumber', 'Vegetables', 30.00, '/Vegetables/Cucumber.jfif', 'Cool and hydrating fresh cucumbers.', 100, 'kg', true, false),
('Sweet Potato', 'Vegetables', 45.00, '/Vegetables/sweetpotato.jfif', 'Nutritious and sweet farm-grown sweet potatoes.', 100, 'kg', true, false),
('Broccoli', 'Vegetables', 150.00, '/Vegetables/Broccoli.jfif', 'Fresh green broccoli, high in fiber and vitamins.', 100, 'kg', true, false),
('Mushroom', 'Vegetables', 50.00, '/Vegetables/ButtonMushrooms.jfif', 'Fresh button mushrooms, perfect for varied dishes.', 100, 'pack', true, false),
('Ridge Gourd', 'Vegetables', 35.00, '/Vegetables/Ridgegourd.jfif', 'Fresh and healthy ridge gourd (peerkangai).', 100, 'kg', true, false),
('Curry Leaves', 'Vegetables', 5.00, '/Vegetables/CurryLeaves.jfif', 'Fresh and aromatic curry leaves.', 100, 'bundle', true, false),
('Ash Gourd', 'Vegetables', 40.00, '/Vegetables/AshGourd.jfif', 'Fresh and hydrating ash gourd.', 100, 'kg', true, false),
('Avarakkai', 'Vegetables', 50.00, '/Vegetables/Avarakkai.jfif', 'Fresh field beans (avarakkai).', 100, 'kg', true, false),
('Baby Corn', 'Vegetables', 60.00, '/Vegetables/BabyCorn.jfif', 'Tender and sweet baby corn.', 100, 'pack', true, false),
('Baby Potato', 'Vegetables', 40.00, '/Vegetables/BabyPotato.jfif', 'Small and creamy baby potatoes.', 100, 'kg', true, false),
('Baji Chilli', 'Vegetables', 45.00, '/Vegetables/BajiChilli.jfif', 'Long and mild chillies for baji.', 100, 'kg', true, false),
('Banana Flower', 'Vegetables', 25.00, '/Vegetables/BananaFlower.jfif', 'Fresh banana flower (vazhaipoo).', 100, 'piece', true, false),
('Banana Stem', 'Vegetables', 20.00, '/Vegetables/BananaStem.jfif', 'Fresh banana stem (vazhaithandu).', 100, 'piece', true, false),
('Brinjal (Eggplant)', 'Vegetables', 40.00, '/Vegetables/BrinjalEggplant.jfif', 'Large purple eggplants.', 100, 'kg', true, false),
('Brinjal (Vari)', 'Vegetables', 40.00, '/Vegetables/BrinjalVari.jfif', 'Striped green brinjals.', 100, 'kg', true, false),
('Capsicum Red', 'Vegetables', 120.00, '/Vegetables/CapsicumRed.jfif', 'Fresh red bell peppers.', 100, 'kg', true, false),
('Capsicum Yellow', 'Vegetables', 120.00, '/Vegetables/CapsicumYellow.jfif', 'Fresh yellow bell peppers.', 100, 'kg', true, false),
('Chow Chow', 'Vegetables', 30.00, '/Vegetables/ChowChow.jfif', 'Fresh and crunchy chow chow.', 100, 'kg', true, false),
('Cluster Beans', 'Vegetables', 40.00, '/Vegetables/ClusterBeans.jfif', 'Fresh cluster beans (kothavarangai).', 100, 'kg', true, false),
('Coconut', 'Vegetables', 30.00, '/Vegetables/Coconut.jfif', 'Fresh and mature coconuts.', 100, 'piece', true, false),
('Karunaikizhangu', 'Vegetables', 50.00, '/Vegetables/Karunaikizhangu.jfif', 'Fresh yam (karunaikizhangu).', 100, 'kg', true, false),
('Kovaikkai', 'Vegetables', 40.00, '/Vegetables/Kovaikkai.jfif', 'Fresh ivy gourd (kovaikkai).', 100, 'kg', true, false),
('Maravalli Kilangu', 'Vegetables', 30.00, '/Vegetables/MaravalliKilangu.jfif', 'Fresh tapioca (maravalli kilangu).', 100, 'kg', true, false),
('Mixed Sprouts', 'Vegetables', 30.00, '/Vegetables/MixedSprouts.jfif', 'Healthy mix of sprouted beans.', 100, 'pack', true, false),
('Moong Green Sprouts', 'Vegetables', 30.00, '/Vegetables/MoongGreenSprouts.jfif', 'Fresh moong green sprouts.', 100, 'pack', true, false),
('Onion (Nasik)', 'Vegetables', 50.00, '/Vegetables/OnionNasik.jfif', 'Premium Nasik onions.', 100, 'kg', true, false),
('Purple Cabbage', 'Vegetables', 60.00, '/Vegetables/PurpleCabbage.jfif', 'Crunchy purple cabbage.', 100, 'kg', true, false),
('Raw Banana', 'Vegetables', 10.00, '/Vegetables/RawBanana.jfif', 'Raw bananas for cooking.', 100, 'piece', true, false),
('Raw Mango', 'Vegetables', 40.00, '/Vegetables/RawMango.jfif', 'Tangy raw mangoes.', 100, 'kg', true, false),
('Seppankizhangu', 'Vegetables', 50.00, '/Vegetables/Seppankizhangu.jfif', 'Fresh taro root (seppankizhangu).', 100, 'kg', true, false),
('Spring Onion', 'Vegetables', 20.00, '/Vegetables/SpringOnion.jfif', 'Fresh spring onions.', 100, 'bundle', true, false),
('Tomato (Bangalore)', 'Vegetables', 40.00, '/Vegetables/TomatoBangalore.jfif', 'Firm Bangalore tomatoes.', 100, 'kg', true, false),
('Zucchini Green', 'Vegetables', 80.00, '/Vegetables/ZucchiniGreen.jfif', 'Fresh green zucchini.', 100, 'kg', true, false),
('Zucchini Yellow', 'Vegetables', 80.00, '/Vegetables/ZucchiniYellow.jfif', 'Fresh yellow zucchini.', 100, 'kg', true, false),
('Nookal', 'Vegetables', 40.00, '/Vegetables/nookal.webp', 'Fresh kohlrabi (nookal).', 100, 'kg', true, false),
('Sweet Corn', 'Vegetables', 30.00, '/Vegetables/sweetcorn.jfif', 'Sweet and juicy corn cobs.', 100, 'piece', true, false),

-- FRUITS
('Apple', 'Fruits', 180.00, '/Fruits/apple.jfif', 'Sweet and crunchy premium apples.', 100, 'kg', true, true),
('Banana (Poovan)', 'Fruits', 60.00, '/Fruits/BananaPoovan.jfif', 'Sweet Poovan bananas.', 100, 'dozen', true, false),
('Guava (White)', 'Fruits', 70.00, '/Fruits/GuavaWhite.jfif', 'Fresh and sweet white guavas.', 100, 'kg', true, false),
('Mango (Banganapalli)', 'Fruits', 150.00, '/Fruits/MangoBanganapalli.jfif', 'Premium Banganapalli mangoes.', 100, 'kg', true, true),
('Musk Melon', 'Fruits', 50.00, '/Fruits/MuskMelon.jfif', 'Sweet and hydrating musk melons.', 100, 'kg', true, true),
('Orange', 'Fruits', 110.00, '/Fruits/orange.jfif', 'Juicy and vitamin C rich oranges.', 100, 'kg', true, false),
('Papaya', 'Fruits', 40.00, '/Fruits/papaya.jfif', 'Ripe and sweet farm papayas.', 100, 'kg', true, false),
('Pineapple', 'Fruits', 60.00, '/Fruits/pineapple.jfif', 'Sweet and tangy fresh pineapples.', 100, 'piece', true, false),
('Pomegranate', 'Fruits', 160.00, '/Fruits/Pomegranate.jfif', 'Premium red pomegranates.', 100, 'kg', true, false),
('Sapota', 'Fruits', 60.00, '/Fruits/Sapota.jfif', 'Sweet and grainy sapota (chikoo).', 100, 'kg', true, false),
('Sweet Lime', 'Fruits', 80.00, '/Fruits/SweetLime.jfif', 'Fresh and juicy mosambi.', 100, 'kg', true, false),
('Watermelon (Kiran)', 'Fruits', 40.00, '/Fruits/WatermelonKiran.jfif', 'Refreshing sweet Kiran watermelons.', 100, 'piece', true, true),
('Strawberry', 'Fruits', 150.00, '/Fruits/Strawberry.jfif', 'Fresh and juicy red strawberries.', 100, 'pack', true, true),
('Kiwi', 'Fruits', 120.00, '/Fruits/kiwi.jfif', 'Zesty and vitamin-rich fresh kiwi.', 100, 'kg', true, false),
('Dragon Fruit', 'Fruits', 80.00, '/Fruits/droganfruit.jfif', 'Exotic and healthy dragon fruit.', 100, 'piece', true, false),
('Banana (Elakki)', 'Fruits', 80.00, '/Fruits/BananaElakki.jfif', 'Small and sweet Elakki bananas.', 100, 'kg', true, false),
('Banana (Karpooravalli)', 'Fruits', 70.00, '/Fruits/BananaKarpooravalli.jfif', 'Sweet Karpooravalli bananas.', 100, 'kg', true, false),
('Banana (Nendhiram)', 'Fruits', 90.00, '/Fruits/BananaNendhiram.jfif', 'Traditional Nendhiram bananas.', 100, 'kg', true, false),
('Amla', 'Fruits', 60.00, '/Fruits/amla.jfif', 'Fresh and healthy Indian gooseberries (amla).', 100, 'kg', true, false),
('Red Banana', 'Fruits', 100.00, '/Fruits/redbanana.jfif', 'Nutritious red bananas.', 100, 'kg', true, false),
('Mango (Senthoora)', 'Fruits', 130.00, '/Fruits/SenthooraMango.webp', 'Sweet Senthoora mangoes.', 100, 'kg', true, true),
('Watermelon (Strips)', 'Fruits', 45.00, '/Fruits/WatermelonStrips.jfif', 'Striped sweet watermelons.', 100, 'piece', true, true),

-- VALLUVAM PRODUCTS
('Cold Pressed Coconut Oil (1L)', 'Valluvam Products', 280, '/Valluvam/coconut-1L.jpg', 'Pure, unrefined cold pressed coconut oil.', 100, '1L', true, false),
('Cold Pressed Groundnut Oil (1L)', 'Valluvam Products', 320, '/Valluvam/ground-1L.jpg', 'Traditional cold pressed groundnut oil.', 100, '1L', true, false),
('Cold Pressed Sesame Oil (1L)', 'Valluvam Products', 450, '/Valluvam/sesame-1L.jpg', 'Rich and aromatic cold pressed sesame oil.', 100, '1L', true, false),
('Natural Palm Jaggery', 'Valluvam Products', 180, '/Valluvam/palm-jaggery.jpeg', 'Authentic palm jaggery with no additives.', 100, '500g', true, false),
('Wild Forest Honey', 'Valluvam Products', 350, '/Valluvam/honey.jpeg', 'Raw, unprocessed honey from deep forests.', 100, '500g', true, false),
('Premium Cashew Nuts (Whole)', 'Valluvam Products', 450, '/Valluvam/CashewNutsWhole.jpg', 'Large, crunchy premium quality cashew nuts.', 100, '250g', true, false),
('A2 Desi Cow Ghee', 'Valluvam Products', 650, '/Valluvam/Ghee250.jpg', 'Pure A2 ghee made using traditional bilona method.', 100, '500ml', true, false),
('Barnyard Millet', 'Valluvam Products', 80.00, '/Valluvam/BarnyardMillet.jpg', 'Healthy barnyard millet.', 100, 'kg', true, false),
('Browntop Millet', 'Valluvam Products', 90.00, '/Valluvam/BrowntopMillet.jpg', 'Healthy browntop millet.', 100, 'kg', true, false),
('Cardamom', 'Valluvam Products', 500.00, '/Valluvam/Cardamom.jpg', 'Aromatic green cardamom.', 100, '100g', true, false),
('Cashew Nuts (Split)', 'Valluvam Products', 400.00, '/Valluvam/CashewSplit.jpg', 'Quality split cashew nuts.', 100, '250g', true, false),
('Cinnamon', 'Valluvam Products', 150.00, '/Valluvam/Cinnamon.jpg', 'Pure cinnamon sticks.', 100, '100g', true, false),
('Cucumber Seeds', 'Valluvam Products', 120.00, '/Valluvam/CucumberSeeds.jpg', 'Healthy cucumber seeds.', 100, '200g', true, false),
('Dry Grapes (Black)', 'Valluvam Products', 180.00, '/Valluvam/DryGrapesBlack.jpg', 'Sweet black raisins.', 100, '250g', true, false),
('Fennel Seeds', 'Valluvam Products', 60.00, '/Valluvam/FennelSeeds.jpg', 'Aromatic fennel seeds.', 100, '100g', true, false),
('Foxtail Millet', 'Valluvam Products', 80.00, '/Valluvam/FoxtailMillet.jpg', 'Healthy foxtail millet.', 100, 'kg', true, false),
('Little Millet', 'Valluvam Products', 80.00, '/Valluvam/LittleMillet.jpg', 'Healthy little millet.', 100, 'kg', true, false),
('Methi', 'Valluvam Products', 40.00, '/Valluvam/Methi.jpg', 'Dried methi seeds.', 100, '100g', true, false),
('Mustard Seeds', 'Valluvam Products', 50.00, '/Valluvam/MustardSeeds.jpg', 'Pure mustard seeds.', 100, '100g', true, false),
('Padam Pisin', 'Valluvam Products', 150.00, '/Valluvam/PadamPisin.jpg', 'Natural almond gum (padam pisin).', 100, '100g', true, false),
('Pearl Millet', 'Valluvam Products', 70.00, '/Valluvam/PearlMillet.jpg', 'Healthy pearl millet (kambu).', 100, 'kg', true, false),
('Pepper (Black)', 'Valluvam Products', 200.00, '/Valluvam/PepperBlack.jpg', 'Pure black pepper.', 100, '100g', true, false),
('Pumpkin Seeds', 'Valluvam Products', 250.00, '/Valluvam/PumpkinSeeds.jpg', 'Healthy pumpkin seeds.', 100, '200g', true, false),
('Sorghum Cholam (White)', 'Valluvam Products', 70.00, '/Valluvam/Sorghum-Cholam(WHITE).jpg', 'Healthy white sorghum.', 100, 'kg', true, false),
('Bay Leaves', 'Valluvam Products', 30.00, '/Valluvam/bayleaves.jpg', 'Aromatic bay leaves.', 100, '50g', true, false),
('Buffalo Ghee (250ml)', 'Valluvam Products', 350.00, '/Valluvam/buffalo(250).jpg', 'Pure buffalo ghee (250ml).', 100, '250ml', true, false),
('Buffalo Ghee (500ml)', 'Valluvam Products', 650.00, '/Valluvam/buffalo(500).jpg', 'Pure buffalo ghee (500ml).', 100, '500ml', true, false),
('Chia Seeds', 'Valluvam Products', 300.00, '/Valluvam/chiaseeds.jpg', 'Healthy chia seeds.', 100, '250g', true, false),
('Clove', 'Valluvam Products', 100.00, '/Valluvam/clove.jpg', 'Aromatic cloves.', 100, '50g', true, false),
('Cold Pressed Coconut Oil (250ml)', 'Valluvam Products', 100.00, '/Valluvam/coconutoil250.jpg', 'Cold pressed coconut oil (250ml).', 100, '250ml', true, false),
('Date', 'Valluvam Products', 200.00, '/Valluvam/date.jpg', 'Sweet and healthy dates.', 100, '500g', true, false),
('Dry Grapes (Green)', 'Valluvam Products', 150.00, '/Valluvam/drygrapesgreen.jpg', 'Sweet green raisins.', 100, '250g', true, false),
('Dry Kiwi', 'Valluvam Products', 350.00, '/Valluvam/drykiwi.jpg', 'Sweet dried kiwi.', 100, '200g', true, false),
('Fig', 'Valluvam Products', 400.00, '/Valluvam/fig.jpg', 'Sweet dried figs.', 100, '250g', true, false),
('Flax Seeds', 'Valluvam Products', 100.00, '/Valluvam/flaxseeds.jpg', 'Healthy flax seeds.', 100, '250g', true, false),
('Foxtail Millet (Thinai)', 'Valluvam Products', 85.00, '/Valluvam/foxtail-thinai.jpg', 'Healthy foxtail millet (thinai).', 100, 'kg', true, false),
('Cold Pressed Groundnut Oil (250ml)', 'Valluvam Products', 120.00, '/Valluvam/groundnutoil250.jpg', 'Cold pressed groundnut oil (250ml).', 100, '250ml', true, false),
('Honey Amla', 'Valluvam Products', 250.00, '/Valluvam/honeyamla.jpg', 'Amla soaked in honey.', 100, '250g', true, false),
('Jeera', 'Valluvam Products', 80.00, '/Valluvam/jeera.jpg', 'Pure cumin seeds.', 100, '100g', true, false),
('Kodo Millet (Varagu)', 'Valluvam Products', 80.00, '/Valluvam/kodo-varagu.jpg', 'Healthy kodo millet (varagu).', 100, 'kg', true, false),
('Natural Palm Jaggery (500g)', 'Valluvam Products', 180.00, '/Valluvam/palm-jaggery(500).jpeg', 'Pure palm jaggery (500g).', 100, '500g', true, false),
('Pista', 'Valluvam Products', 500.00, '/Valluvam/pista.jpg', 'Crunchy pistas.', 100, '250g', true, false),
('Cold Pressed Sesame Oil (500ml)', 'Valluvam Products', 250.00, '/Valluvam/sesame500.jpg', 'Cold pressed sesame oil (500ml).', 100, '500ml', true, false),
('Star Anise', 'Valluvam Products', 100.00, '/Valluvam/staranise.jpg', 'Aromatic star anise.', 100, '50g', true, false),
('Sunflower Seeds', 'Valluvam Products', 150.00, '/Valluvam/sunflowerseeds.jpg', 'Healthy sunflower seeds.', 100, '200g', true, false),
('Walnut', 'Valluvam Products', 600.00, '/Valluvam/walnut.jpg', 'Crunchy walnuts.', 100, '250g', true, false);



